import { Header, Footer } from '@/components';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-black text-white flex flex-col">
            <Header />
            <main className="flex-1 pt-32 pb-20 container mx-auto px-4">
                <h1 className="text-4xl font-heading font-bold mb-4" style={{ color: '#ffffff' }}>TERMS OF SERVICE</h1>
                <p style={{ color: '#ff8552', fontSize: '1.125rem', fontWeight: 600, marginBottom: '8px' }}>OpenAnalyst Inc.</p>
                <p style={{ color: '#9ca3af', marginBottom: '32px' }}>Last Updated: December 19, 2025</p>

                <div className="prose prose-invert max-w-none" style={{ color: '#d1d5db' }}>
                    <p>These Terms of Service (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you and OpenAnalyst Inc. (together with its affiliates, &ldquo;OpenAnalyst&rdquo;, &ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo; or &ldquo;us&rdquo;) governing your access to and use of our products, services, software platform, mobile application (the &ldquo;App&rdquo;), website (the &ldquo;Site&rdquo;), and all related features and functionality (collectively, the &ldquo;Services&rdquo;).</p>

                    <div style={{ backgroundColor: '#18181b', border: '1px solid rgba(255, 133, 82, 0.3)', borderRadius: '12px', padding: '24px', margin: '24px 0' }}>
                        <p style={{ fontWeight: 700, color: '#ff8552', marginBottom: '8px' }}>IMPORTANT:</p>
                        <p style={{ color: '#d1d5db' }}>BY CLICKING &ldquo;I AGREE&rdquo; OR ANY SIMILAR BUTTON, REGISTERING FOR AN ACCOUNT, DOWNLOADING THE APP, ACCESSING OR USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE. IF YOU DO NOT AGREE TO THESE TERMS, YOU HAVE NO RIGHT TO ACCESS OR USE THE SERVICES.</p>
                    </div>

                    <p>If you accept or agree to these Terms on behalf of a company or other legal entity, you represent and warrant that: (i) you have full legal authority to bind such entity to these Terms; (ii) you have read and understand these Terms; and (iii) you agree to these Terms on behalf of the entity you represent. In such event, &ldquo;you&rdquo; and &ldquo;your&rdquo; will refer to such entity.</p>

                    <p>Any personal data you submit to us or which we collect is governed by our Privacy Policy. By using the Services, you acknowledge that you have reviewed the Privacy Policy. If you and OpenAnalyst enter into a data processing addendum or agreement (each, a &ldquo;DPA&rdquo;), the terms of the DPA, which are incorporated herein by reference, will apply to the extent OpenAnalyst processes any personal data on your behalf.</p>

                    <div style={{ backgroundColor: '#18181b', border: '1px solid rgba(255, 133, 82, 0.3)', borderRadius: '12px', padding: '24px', margin: '24px 0' }}>
                        <p style={{ fontWeight: 700, color: '#ff8552' }}>ARBITRATION NOTICE: THIS AGREEMENT CONTAINS A BINDING ARBITRATION PROVISION AND CLASS ACTION WAIVER IN SECTION 15. PLEASE READ SECTION 15 CAREFULLY AS IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.</p>
                    </div>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>1. Definitions</h2>
                    <p>The following terms shall have the meanings set forth below. Additional definitions may appear throughout these Terms.</p>
                    <ul style={{ color: '#d1d5db', listStyleType: 'disc', paddingLeft: '24px' }}>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;Account&rdquo;</strong> means your registered account with OpenAnalyst required to access and use the Services.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;Account Owner&rdquo;</strong> means the person or entity that registers for the Services and is the contracting party under these Terms.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;AI Functions&rdquo;</strong> means features and capabilities offered as part of the Services that utilize artificial intelligence, machine learning, or similar technologies developed by OpenAnalyst and/or third-party AI providers.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;AI Content&rdquo;</strong> means collectively Input, Output, and User Generated Content used with or generated by AI Functions.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;Confidential Information&rdquo;</strong> means any non-public, proprietary, or confidential information of OpenAnalyst, including but not limited to trade secrets, technical data, business strategies, customer information, and product plans.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;Data Protection Laws&rdquo;</strong> means all applicable data protection and privacy laws, including but not limited to the General Data Protection Regulation (GDPR), California Consumer Privacy Act (CCPA), California Privacy Rights Act (CPRA), and any other legislation applicable to the processing of personal information.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;Input&rdquo;</strong> means any content, information, data, or materials you provide to the AI Functions for processing.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;Intellectual Property Rights&rdquo;</strong> means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights, and other intellectual property rights as may now exist or hereafter come into existence, and all applications and registrations thereof.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;Output&rdquo;</strong> means the results, analysis, visualizations, reports, code, or other content generated and returned by the AI Functions in response to your Input.</li>
                        <li><strong style={{ color: '#ffffff' }}>&ldquo;User Generated Content&rdquo;</strong> means any content, information, data, files, or materials that you provide, submit, upload, publish, or otherwise make available to the Services.</li>
                    </ul>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>2. Description of Services</h2>
                    <p>OpenAnalyst is an advanced AI-powered analytics platform that enables users to analyze complex data, generate insights, create visualizations, and produce reports through artificial intelligence and machine learning technologies. The Services allow you to:</p>
                    <ul style={{ color: '#d1d5db', listStyleType: 'disc', paddingLeft: '24px' }}>
                        <li>Upload and connect various data sources including files, databases, and third-party integrations</li>
                        <li>Interact with your data through natural language queries and AI-powered analysis</li>
                        <li>Generate visualizations, charts, reports, and analytical outputs</li>
                        <li>Utilize AI Functions to process, analyze, and derive insights from your data</li>
                        <li>Export and share analysis results and reports</li>
                    </ul>
                    <p>OpenAnalyst reserves the right to modify, enhance, or discontinue any features or functionality of the Services at any time without prior notice, provided that such modifications do not materially diminish the core functionality of the Services you have paid for.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>3. Account Registration and Eligibility</h2>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>3.1 Age and Capacity</h3>
                    <p>You must be at least 18 years of age or the age of legal majority in your jurisdiction, whichever is greater, to use the Services. By registering for an Account, you represent and warrant that you meet these age requirements and have the legal capacity to enter into binding contracts.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>3.2 Account Information</h3>
                    <p>During registration, you must provide accurate, current, and complete information as requested, including your name, email address, and payment information. You agree to maintain and promptly update your Account information to keep it accurate, current, and complete.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>3.3 Account Security</h3>
                    <p>You are solely responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your Account. You agree to:</p>
                    <ul style={{ color: '#d1d5db', listStyleType: 'disc', paddingLeft: '24px' }}>
                        <li>Use a strong, unique password for your Account</li>
                        <li>Not share your Account credentials with any third party</li>
                        <li>Immediately notify OpenAnalyst if you suspect any unauthorized use of your Account</li>
                        <li>Log out of your Account at the end of each session when using shared devices</li>
                    </ul>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>3.4 Account Ownership and Transfer</h3>
                    <p>Your Account is personal to you and may not be transferred, sold, or assigned to any other person or entity without OpenAnalyst&apos;s prior written consent.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>4. Subscription Plans and Billing</h2>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>4.1 Subscription Fees</h3>
                    <p>Access to the Services requires a paid subscription, the fees for which are set forth on our pricing page (the &ldquo;Subscription Fees&rdquo;). All Subscription Fees are exclusive of applicable taxes.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>4.2 Payment Terms</h3>
                    <p>You agree to provide valid payment information at the time of registration. Subscription Fees will be charged automatically on a recurring basis until you cancel your subscription.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>4.3 Free Trial Period</h3>
                    <p>OpenAnalyst may, at its sole discretion, offer a free trial period for new users. Your subscription will automatically convert to a paid subscription at the end of the trial period unless you cancel before the trial expires.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>4.4 Price Changes</h3>
                    <p>OpenAnalyst reserves the right to modify Subscription Fees at any time. We will provide you with at least thirty (30) days&apos; advance notice of any fee increases.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>4.5 Refund Policy</h3>
                    <p>You may request a refund of Subscription Fees within fourteen (14) days of your initial purchase or subscription renewal, provided that you have not made material use of the Services during that period. Material use is defined as:</p>
                    <ul style={{ color: '#d1d5db', listStyleType: 'disc', paddingLeft: '24px' }}>
                        <li>Uploading or analyzing data exceeding 100 MB</li>
                        <li>Generating more than 25 AI-powered analyses or reports</li>
                        <li>Creating more than 10 visualizations or dashboards</li>
                    </ul>
                    <p>After the 14-day refund period, all Subscription Fees are non-refundable and non-reimbursable under any circumstances.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>4.6 Payment Failures</h3>
                    <p>If payment fails for any reason, OpenAnalyst may suspend or terminate your access to the Services until payment is successfully processed.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>5. AI Functions and User Generated Content</h2>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>5.1 Ownership of AI Functions</h3>
                    <p>OpenAnalyst and/or its licensors exclusively own all right, title, and interest in and to the AI Functions, including all associated Intellectual Property Rights.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>5.2 Ownership of User Generated Content</h3>
                    <p>You retain all ownership rights in your User Generated Content. However, by providing User Generated Content to the Services, you grant OpenAnalyst a worldwide, non-exclusive, royalty-free, sublicensable license to use, copy, reproduce, process, adapt, modify, publish, transmit, display, and distribute your User Generated Content solely for the purposes of providing and improving the Services.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>5.3 Input and Output</h3>
                    <p>When you provide Input to the AI Functions, you will receive Output generated by the AI Functions. Both Input and Output are considered your User Generated Content, and you own all rights to both. However, you acknowledge that:</p>
                    <ul style={{ color: '#d1d5db', listStyleType: 'disc', paddingLeft: '24px' }}>
                        <li>Output may not be unique and similar Output may be generated for other users</li>
                        <li>Output is generated by AI and may contain errors, inaccuracies, or hallucinations</li>
                        <li>You should independently verify the accuracy of Output before relying on it</li>
                    </ul>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>5.4 Your Responsibilities for User Generated Content</h3>
                    <p>You are solely responsible for all User Generated Content you provide to the Services. You represent and warrant that your User Generated Content does not infringe any third-party rights, does not violate any applicable laws, does not contain malware, and does not contain false, misleading, defamatory, obscene, or unlawful content.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>5.5 Use of AI Content for Improvement</h3>
                    <p>OpenAnalyst may collect and use aggregated, anonymized data derived from your use of the AI Functions to maintain and improve the AI Functions, develop new features, ensure security, and comply with applicable laws.</p>
                    <div style={{ backgroundColor: '#18181b', border: '1px solid rgba(255, 133, 82, 0.3)', borderRadius: '12px', padding: '24px', margin: '24px 0' }}>
                        <p style={{ fontWeight: 700, color: '#ff8552' }}>IMPORTANT: OpenAnalyst will not, and contractually restricts third-party AI providers from, using your User Generated Content to train AI models or improve services for general use by other parties. Your data will only be used to provide the Services to you and for the limited purposes stated above.</p>
                    </div>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>5.6 Prohibited Uses of AI Functions</h3>
                    <p>You agree not to use the AI Functions or Output to develop competing AI products, reverse engineer models, mislead others, generate illegal content, or circumvent usage limits.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>5.7 AI Output Disclaimer</h3>
                    <div style={{ backgroundColor: '#18181b', border: '1px solid rgba(255, 255, 255, 0.1)', borderRadius: '12px', padding: '24px', margin: '24px 0' }}>
                        <p style={{ color: '#d1d5db', textTransform: 'uppercase', fontSize: '0.875rem' }}>AI-GENERATED OUTPUT IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTY OF ANY KIND. OUTPUT MAY CONTAIN ERRORS, INACCURACIES, OR MISLEADING INFORMATION. YOU MUST INDEPENDENTLY VERIFY ALL OUTPUT BEFORE RELYING ON IT FOR ANY PURPOSE, INCLUDING BUT NOT LIMITED TO BUSINESS DECISIONS, FINANCIAL ANALYSIS, LEGAL MATTERS, OR MEDICAL ADVICE. OPENANALYST IS NOT LIABLE FOR ANY CONSEQUENCES RESULTING FROM YOUR RELIANCE ON OUTPUT.</p>
                    </div>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>6. Data Processing and Privacy</h2>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>6.1 Data Collection and Use</h3>
                    <p>OpenAnalyst collects and processes personal data as described in our Privacy Policy. By using the Services, you consent to the collection, processing, and use of your personal data in accordance with the Privacy Policy and applicable Data Protection Laws.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>6.2 Data Processing Agreement</h3>
                    <p>To the extent that OpenAnalyst processes personal data on your behalf as a data processor, the terms of our Data Processing Agreement (&ldquo;DPA&rdquo;) shall apply.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>6.3 Cookies and Analytics</h3>
                    <p>OpenAnalyst uses cookies, web beacons, and similar tracking technologies to enhance your experience, analyze usage patterns, and improve the Services.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>6.4 Third-Party Integrations</h3>
                    <p>The Services may allow you to connect third-party services, databases, or platforms. You are responsible for ensuring that you have the right to grant such access.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>6.5 Data Retention and Deletion</h3>
                    <p>OpenAnalyst will retain your User Generated Content and Account data for as long as your Account remains active and for a reasonable period thereafter. Upon termination of your Account, OpenAnalyst reserves the right to delete all of your data. Deleted data cannot be recovered.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>7. Intellectual Property Rights</h2>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>7.1 OpenAnalyst Proprietary Rights</h3>
                    <p>All content, features, functionality, software, algorithms, and other materials made available through the Services are the exclusive property of OpenAnalyst or its licensors and are protected by intellectual property laws.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>7.2 Restrictions on Use</h3>
                    <p>You agree not to copy, modify, distribute, sell, or lease any part of the Services; reverse engineer, decompile, or disassemble the Services; remove proprietary notices; use the Services to develop competing products; or access the Services through automated means.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>7.3 Trademarks</h3>
                    <p>&ldquo;OpenAnalyst&rdquo; and the OpenAnalyst logo are the property of OpenAnalyst or its licensors. You may not use these marks without prior written consent.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>7.4 Feedback</h3>
                    <p>If you provide OpenAnalyst with any feedback, suggestions, ideas, or recommendations, you grant OpenAnalyst a perpetual, irrevocable, worldwide, royalty-free license to use such Feedback for any purpose without any obligation or compensation to you.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>8. Acceptable Use and Prohibited Conduct</h2>
                    <p>You agree to use the Services only for lawful purposes and in accordance with these Terms. You specifically agree not to:</p>
                    <ul style={{ color: '#d1d5db', listStyleType: 'disc', paddingLeft: '24px' }}>
                        <li>Violate any applicable law or regulation</li>
                        <li>Infringe on the rights of any third party</li>
                        <li>Upload unlawful, harmful, threatening, abusive, or objectionable content</li>
                        <li>Upload viruses, malware, or other malicious code</li>
                        <li>Attempt to gain unauthorized access to the Services</li>
                        <li>Interfere with or disrupt the Services</li>
                        <li>Impersonate any person or entity</li>
                        <li>Engage in activities that could impair the functioning of the Services</li>
                        <li>Send spam or unsolicited communications</li>
                        <li>Harvest information about other users without consent</li>
                        <li>Circumvent security features or access controls</li>
                        <li>Share your Account credentials with any third party</li>
                    </ul>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>9. Third-Party Services and Links</h2>
                    <p>The Services may contain links to third-party websites, services, or resources that are not owned or controlled by OpenAnalyst. OpenAnalyst does not endorse and is not responsible for the content, privacy policies, or practices of any Third-Party Services. You acknowledge and agree that OpenAnalyst is not liable for any damage or loss caused by your use of or reliance on any Third-Party Services.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>10. Disclaimers and Warranties</h2>
                    <div style={{ backgroundColor: '#18181b', border: '1px solid rgba(255, 255, 255, 0.1)', borderRadius: '12px', padding: '24px', margin: '24px 0' }}>
                        <p style={{ color: '#d1d5db', textTransform: 'uppercase', fontSize: '0.875rem' }}>THE SERVICES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, OPENANALYST DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.</p>
                    </div>
                    <p>YOU USE THE SERVICES AT YOUR OWN RISK. ANY MATERIAL, DATA, OR INFORMATION DOWNLOADED OR OTHERWISE OBTAINED THROUGH USE OF THE SERVICES IS ACCESSED AT YOUR OWN DISCRETION AND RISK.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>11. Limitation of Liability</h2>
                    <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL OPENANALYST, ITS AFFILIATES, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS INTERRUPTION.</p>
                    <p>OPENANALYST&apos;S TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE GREATER OF: (I) THE TOTAL SUBSCRIPTION FEES PAID BY YOU IN THE TWELVE (12) MONTHS PRECEDING THE EVENT, OR (II) ONE HUNDRED DOLLARS ($100).</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>12. Indemnification</h2>
                    <p>You agree to indemnify, defend, and hold harmless OpenAnalyst, its affiliates, and their respective directors, officers, employees, agents, licensors, and service providers from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees arising from or relating to your use of the Services, your violation of these Terms, your violation of any applicable laws, your User Generated Content, or any negligent or wrongful conduct by you.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>13. Confidential Information</h2>
                    <p>You acknowledge that you may have access to Confidential Information of OpenAnalyst. You agree to keep all Confidential Information strictly confidential, not disclose it to any third party, use it solely for the purpose of using the Services, and protect it using reasonable care. These confidentiality obligations shall survive termination of these Terms for a period of three (3) years.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>14. Termination</h2>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>14.1 Termination by You</h3>
                    <p>You may terminate your Account at any time by using the account deletion feature within the Services or by sending written notice to OpenAnalyst at info@openanalyst.com. Termination will be effective at the end of your current billing cycle.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>14.2 Termination by OpenAnalyst</h3>
                    <p>OpenAnalyst may suspend or terminate your Account and access to the Services immediately, without prior notice or liability, for violation of these Terms, suspected fraudulent activity, failure to pay, extended inactivity, or to protect the security of the Services.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>14.3 Effect of Termination</h3>
                    <p>Upon termination, your right to access the Services will immediately cease, OpenAnalyst may delete all of your data, and you will remain responsible for all fees incurred prior to termination.</p>
                    <div style={{ backgroundColor: '#18181b', border: '1px solid rgba(255, 133, 82, 0.3)', borderRadius: '12px', padding: '24px', margin: '24px 0' }}>
                        <p style={{ fontWeight: 700, color: '#ff8552' }}>WARNING: Deleted data cannot be recovered. You are responsible for exporting and backing up any data you wish to retain before terminating your Account.</p>
                    </div>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>14.4 Sole Remedy</h3>
                    <p>IF YOU ARE DISSATISFIED WITH THE SERVICES OR WITH ANY TERMS, CONDITIONS, RULES, POLICIES, OR PRACTICES OF OPENANALYST, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICES AND TERMINATE YOUR ACCOUNT.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>15. Dispute Resolution and Arbitration</h2>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>15.1 Informal Dispute Resolution</h3>
                    <p>Before initiating any formal dispute resolution proceedings, you agree to first contact OpenAnalyst and attempt to resolve the dispute informally. You and OpenAnalyst agree to negotiate in good faith for at least thirty (30) days before pursuing formal dispute resolution.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>15.2 Binding Arbitration</h3>
                    <div style={{ backgroundColor: '#18181b', border: '1px solid rgba(255, 133, 82, 0.3)', borderRadius: '12px', padding: '24px', margin: '24px 0' }}>
                        <p style={{ fontWeight: 700, color: '#ff8552' }}>YOU AND OPENANALYST AGREE THAT ANY DISPUTE, CLAIM, OR CONTROVERSY ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICES WILL BE SETTLED BY BINDING ARBITRATION. THIS MEANS THAT YOU AND OPENANALYST BOTH WAIVE THE RIGHT TO A TRIAL BY JURY AND THE RIGHT TO PARTICIPATE IN A CLASS ACTION.</p>
                    </div>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>15.3 Arbitration Rules and Procedures</h3>
                    <p>The arbitration will be administered by the American Arbitration Association (&ldquo;AAA&rdquo;) in accordance with the AAA&apos;s Commercial Arbitration Rules. The arbitration will be conducted by a single neutral arbitrator. Unless agreed otherwise, the arbitration will take place in Delaware.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>15.4 Exceptions to Arbitration</h3>
                    <p>Either party may bring an individual action in small claims court or seek injunctive relief to prevent infringement of Intellectual Property Rights.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>15.5 Class Action Waiver</h3>
                    <p>YOU AND OPENANALYST AGREE THAT ANY ARBITRATION OR COURT PROCEEDING WILL BE CONDUCTED ON AN INDIVIDUAL BASIS AND NOT AS A CLASS ACTION, CONSOLIDATED ACTION, OR REPRESENTATIVE ACTION.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>15.6 Arbitration Fees</h3>
                    <p>If your claim is for $10,000 or less, OpenAnalyst will pay all filing, administrative, and arbitrator fees. If your claim exceeds $10,000, fees will be governed by the AAA Rules.</p>

                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>15.7 Opt-Out Right</h3>
                    <p>You may opt out of this arbitration agreement by sending written notice to OpenAnalyst within thirty (30) days of first accepting these Terms.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>16. Governing Law and Jurisdiction</h2>
                    <p>These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States of America, without regard to its conflict of law principles. You and OpenAnalyst agree to submit to the exclusive jurisdiction of the state and federal courts located in Delaware.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>17. General Provisions</h2>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.1 Entire Agreement</h3>
                    <p>These Terms, together with the Privacy Policy and any other policies referenced herein, constitute the entire agreement between you and OpenAnalyst regarding the Services.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.2 Amendments</h3>
                    <p>OpenAnalyst reserves the right to modify these Terms at any time. We will provide notice of material changes by posting the updated Terms and updating the &ldquo;Last Updated&rdquo; date.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.3 Waiver</h3>
                    <p>No waiver of any term or condition shall be deemed a further or continuing waiver of such term or any other term.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.4 Severability</h3>
                    <p>If any provision is found invalid, it shall be modified to the extent necessary or severed. The remaining provisions shall continue in full force.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.5 Assignment</h3>
                    <p>You may not assign these Terms without OpenAnalyst&apos;s prior written consent. OpenAnalyst may freely assign these Terms without restriction.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.6 No Third-Party Beneficiaries</h3>
                    <p>These Terms are for the benefit of you and OpenAnalyst only and do not create rights for any third parties.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.7 Force Majeure</h3>
                    <p>OpenAnalyst shall not be liable for any failure or delay in performance due to causes beyond its reasonable control.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.8 Relationship of Parties</h3>
                    <p>No agency, partnership, joint venture, or employer-employee relationship is created by these Terms.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.9 Export Control</h3>
                    <p>The Services may be subject to export control laws. You agree to comply with all applicable export and re-export control laws and regulations.</p>
                    <h3 style={{ color: '#ffffff', fontSize: '1.125rem', fontWeight: 600, marginTop: '24px', marginBottom: '12px' }}>17.10 Electronic Communications</h3>
                    <p>By using the Services, you consent to receive electronic communications from OpenAnalyst. You agree that all electronic communications satisfy any legal requirement that such communications be in writing.</p>

                    <h2 style={{ color: '#ffffff', fontSize: '1.5rem', fontWeight: 700, marginTop: '48px', marginBottom: '16px' }}>18. Contact Information</h2>
                    <p>If you have any questions, comments, or concerns about these Terms or the Services, please contact us at:</p>
                    <div style={{ backgroundColor: '#18181b', borderRadius: '12px', padding: '24px', margin: '24px 0', border: '1px solid rgba(255, 255, 255, 0.05)' }}>
                        <p style={{ color: '#ffffff', fontWeight: 700, marginBottom: '8px' }}>OpenAnalyst Inc.</p>
                        <p style={{ color: '#9ca3af' }}>Email: <a href="mailto:info@openanalyst.com" style={{ color: '#ff8552' }}>info@openanalyst.com</a></p>
                    </div>

                    <div style={{ backgroundColor: '#18181b', border: '1px solid rgba(255, 133, 82, 0.3)', borderRadius: '12px', padding: '24px', margin: '48px 0 0' }}>
                        <p style={{ color: '#d1d5db', textTransform: 'uppercase', fontSize: '0.875rem' }}>BY CLICKING &ldquo;I AGREE&rdquo; OR BY ACCESSING OR USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE, UNDERSTAND THEM, AND AGREE TO BE BOUND BY THEM.</p>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
